use ibd_tp;
delete from Partido;
insert into Partido values('MG', 'DEM');
insert into Partido values('MG', 'PC do B');
insert into Partido values('MG', 'PCB');
insert into Partido values('MG', 'PCO');
insert into Partido values('MG', 'PDT');
insert into Partido values('MG', 'PHS');
insert into Partido values('MG', 'PMDB');
insert into Partido values('MG', 'PMN');
insert into Partido values('MG', 'PP');
insert into Partido values('MG', 'PPS');
insert into Partido values('MG', 'PR');
insert into Partido values('MG', 'PRB');
insert into Partido values('MG', 'PRP');
insert into Partido values('MG', 'PRTB');
insert into Partido values('MG', 'PSB');
insert into Partido values('MG', 'PSC');
insert into Partido values('MG', 'PSDB');
insert into Partido values('MG', 'PSDC');
insert into Partido values('MG', 'PSL');
insert into Partido values('MG', 'PSOL');
insert into Partido values('MG', 'PSTU');
insert into Partido values('MG', 'PT');
insert into Partido values('MG', 'PT do B');
insert into Partido values('MG', 'PTB');
insert into Partido values('MG', 'PTC');
insert into Partido values('MG', 'PTN');
insert into Partido values('MG', 'PV');