use ibd_tp;
DELETE FROM Partido;
INSERT INTO Partido(uf,sigla) VALUES('MG', 'DEM');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PC do B');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PCB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PCO');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PDT');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PHS');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PMDB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PMN');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PP');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PPS');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PR');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PRB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PRP');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PRTB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSC');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSDB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSDC');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSL');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSOL');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PSTU');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PT');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PT do B');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PTB');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PTC');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PTN');
INSERT INTO Partido(uf,sigla) VALUES('MG', 'PV');