use ibd_tp;
DELETE FROM Partido_Comite;
INSERT INTO Partido_Comite VALUES(12, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(5, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(7, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(21, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(19, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(26, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(16, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(3, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(11, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(1, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(25, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(15, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(27, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(17, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(20, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(2, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(23, 'Comitê Financeiro Único');
INSERT INTO Partido_Comite VALUES(22, 'Comitê Financeiro Distrital/Estadual para Senador da República');
INSERT INTO Partido_Comite VALUES(22, 'Comitê Financeiro Distrital/Estadual para Deputado Federal');
INSERT INTO Partido_Comite VALUES(6, 'Comitê Financeiro Distrital/Estadual para Deputado Federal');
INSERT INTO Partido_Comite VALUES(22, 'Comitê Financeiro Distrital/Estadual para Deputado Estadual');
INSERT INTO Partido_Comite VALUES(6, 'Comitê Financeiro Distrital/Estadual para Deputado Estadual');
