use ibd_tp;
delete from Partido_Comite;
insert into Partido_Comite values('MG', 'PRB', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PDT', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PMDB', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PSTU', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PSL', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PTN', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PSC', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PCB', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PR', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'DEM', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PTC', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PSB', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PV', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PSDB', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PSOL', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PC do B', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PT do B', 'Comitê Financeiro Único');
insert into Partido_Comite values('MG', 'PT', 'Comitê Financeiro Distrital/Estadual para Senador da República');
insert into Partido_Comite values('MG', 'PT', 'Comitê Financeiro Distrital/Estadual para Deputado Federal');
insert into Partido_Comite values('MG', 'PHS', 'Comitê Financeiro Distrital/Estadual para Deputado Federal');
insert into Partido_Comite values('MG', 'PT', 'Comitê Financeiro Distrital/Estadual para Deputado Estadual');
insert into Partido_Comite values('MG', 'PHS', 'Comitê Financeiro Distrital/Estadual para Deputado Estadual');